version: '3.3'

# Container for Web Handler

services:
  webserver:
    env_file:
      - .env
    depends_on:
      - db
      - php
    build: 
      context: ./Dockerfiles
      dockerfile: dockerfile-frontend
    image: glue-frontend
    container_name: glue-frontend
    restart: unless-stopped
    working_dir: /public_html
    ports:
      - 80:80
    networks:
      - glue

# Backend tier start here
  php:
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ./Dockerfiles
      dockerfile: dockerfile-backend
    image: glue-backend
    container_name: glue-backend
    restart: unless-stopped
    working_dir: /public_html
    expose:
      - 9000
    networks:
      - glue
    entrypoint: ["sh", "/startup.sh"]

# Database Tier start Here
  db:
    env_file:
      - .env
    build:
      context: ./Dockerfiles
      dockerfile: dockerfile-backend
    image: glue-db
    container_name: glue-db
    restart: unless-stopped
    expose:
      - 3306
    networks:
      - glue



networks:
  glue:

